---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by a.
--- DateTime: 2021/4/2 15:51
---
import "UniytEngine"
function main()

    print("it works")
    print("hello?")
    print("测试")

end